# Generated by Django 3.2.12 on 2023-07-11 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finishingTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='startingTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
