# Generated by Django 4.2.3 on 2023-07-28 09:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230711_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
