# Generated by Django 4.2.3 on 2023-08-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history',
            new_name='hist',
        ),
    ]
