# Generated by Django 4.2.3 on 2023-08-23 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_history_hist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist',
            name='action',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hist',
            name='finish',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
